### ISSUE TITLE
[BUG] is still formio supported by angularJS

### ISSUE THREAD

**Issue by belghithb** [formio/ngFormio#708]
Hello,

I tried to add formio to my existing angularjs project trying "Complete Installation" in readme, 
 1/ I added 
<link rel="stylesheet" href="https://rawgit.com/formio/ngFormio/master/dist/formio-complete.min.css" />
<script src="https://rawgit.com/formio/ngFormio/master/dist/formio-complete.min.js"></script>
to index.html file.

2/ I imported formio to app.js file.

When running the application it throws this error Uncaught Error: [$injector:modulerr]   at angular.js:38:1
    at angular.js:4120:15
    at s (angular.js:323:11)
    at g (angular.js:4081:5)
    at ab (angular.js:4007:11)
    at d (angular.js:1445:20)
    at tc (angular.js:1466:12)
    at Jd (angular.js:1360:5)
    at HTMLDocument.<anonymous> (angular.js:26125:5)
    at j (jquery.min.js:2:2713

But when i checked the two linkes "https://rawgit.com/formio/ngFormio/master/dist/formio-complete.min.css"  and "https://rawgit.com/formio/ngFormio/master/dist/formio-complete.min.js" they returns "404".

Any help please. thanks in advance

**Comment by wag110894** [comment]
Hello @belghithb,

Can you take a look here: https://github.com/formio/angular?

**Comment by belghithb** [comment]
Hello @wag110894,
This library  https://github.com/formio/angular suppose to be working with angular 2+ no?
